# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "@Autoweird.fm"
email: ""
description: "@Autoweird.fm ist der regelmäßig erscheinende Podcast rund um die
  Themen Software Entwicklung, Agilität und Software Craftsmanship."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://autoweirdfm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: autoweirdfm
github_username:  autoweirdfm

# Podcast rss feed configuration
podcast_url: https://autoweirdfm.github.io
podcast_album_art: /assets/images/autoweirdfm_logo_500x500.png
podcast_title: "@Autoweird.fm"
podcast_owner: "@Autoweird.fm Team"
podcast_email: ""
podcast_category: "Technik"
podcast_subcategory_one: "Software Entwicklung"
podcast_subcategory_two: "Software Craftsmanship"
podcast_explicit: "no"
podcast_author: "Holger Grosse-Plankermann und Benedikt Ritter"
podcast_description: Regelmäßiger Podcast rund um Software Entwicklung, Agilität und Software Craftsmanship.
podcast_summary: Holger Grosse-Plankermann und Benedikt Ritter verabreden sich zu einem regelmäßigen Feierabendbierchen, bei dem kräftig über relevante Themen rund um Software Entwicklung, Agilität und Software Craftsmanship diskutiert und philosophiert wird.
podcast_subtitle: Bier - Software Entwicklung - Philosphieren

permalink: /:year/:month/:day/:title/
paginate: 10

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
